version: '3.7'
services:
  instagram-database:
    image: mysql:8.0
    container_name: instagram-db
    networks:
      - khuthon_net
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD='1234'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  instagram-service:
    image: instagram-service:v1
    container_name: instagram-service
    ports:
      - 8000:8000
    depends_on: 
      - instagram-database
    networks:
      - khuthon_net
  mail-service:
    image: mail-service:v1
    env_file: ./.env
    environment:
      - GMAIL=$GMAIL
      - GMAIL_PASSWORD=$GMAIL_PASSWORD
    container_name: mail-service
    ports:
      - 3000:3000
    networks:
      - khuthon_net
    command: ["npm","start"]

networks:
  khuthon_net:

